ALLOWED_UPLOAD_SUFFIXES = {".txt", ".md", ".markdown", ".docx", ".pdf"}
DEFAULT_MIN_CHARS = 300
DEFAULT_TARGET_CHARS = 900
DEFAULT_MAX_CHARS = 1200
DEFAULT_OVERLAP_SENTENCES = 2
CORS_ALLOW_ORIGINS = ["http://127.0.0.1:5173", "http://localhost:5173"]
